// src/content/components/GitHubSection.svelte
<script lang="ts">
  import gitLogo from '../../assets/git.svg'
  import { appState, setSelectedRepo, setSelectedBranch, fetchRepos } from '../store.svelte'

  interface Props {
    connected?: boolean
    onConnect?: () => void
    onDisconnect?: () => void
  }

  let { connected = false, onConnect, onDisconnect }: Props = $props()

  function handleRepoChange(event: Event) {
    const value = (event.target as HTMLSelectElement).value
    setSelectedRepo(value)
  }

  function handleBranchChange(event: Event) {
    const value = (event.target as HTMLSelectElement).value
    setSelectedBranch(value)
  }

  function handleRefresh() {
    fetchRepos(true) // force refresh
  }
</script>

<svelte:head>
  {@html `<style>
    @keyframes git8git-spin {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }
    .git8git-spinning {
      animation: git8git-spin 1s linear infinite !important;
    }
  </style>`}
</svelte:head>

<div style="display: flex !important; flex-direction: column !important; gap: 12px !important;">
  <div style="font-size: 11px !important; font-weight: 600 !important; color: #737373 !important; text-transform: uppercase !important; letter-spacing: 0.05em !important;">
    GitHub
  </div>

  {#if connected}
    <div style="display: flex !important; flex-direction: column !important; gap: 8px !important;">
      <div style="display: flex !important; align-items: center !important; justify-content: space-between !important;">
        <div style="display: flex !important; align-items: center !important; gap: 8px !important; font-size: 14px !important; color: #10b981 !important;">
          <img src={gitLogo} alt="" style="width: 16px !important; height: 16px !important;" />
          <span>Connected</span>
        </div>
        <button
          type="button"
          style="font-size: 12px !important; color: #737373 !important; background: none !important; border: none !important; cursor: pointer !important;"
          onclick={onDisconnect}
        >
          Disconnect
        </button>
      </div>

      {#if appState.reposError}
        <div style="font-size: 12px !important; color: #ef4444 !important; padding: 8px !important; background: #fef2f2 !important; border-radius: 6px !important;">
          {appState.reposError}
        </div>
      {/if}

      <div style="display: flex !important; flex-direction: column !important; gap: 8px !important;">
        <label style="display: flex !important; flex-direction: column !important; gap: 4px !important;">
          <div style="display: flex !important; align-items: center !important; justify-content: space-between !important;">
            <span style="font-size: 12px !important; color: #737373 !important;">Repository</span>
            <button
              type="button"
              onclick={handleRefresh}
              disabled={appState.reposLoading}
              title="Refresh repositories"
              style="
                background: none !important;
                border: none !important;
                padding: 2px !important;
                cursor: pointer !important;
                color: #737373 !important;
                display: flex !important;
                align-items: center !important;
                justify-content: center !important;
              "
            >
              <svg
                class={appState.reposLoading ? 'git8git-spinning' : ''}
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
                <path d="M3 3v5h5" />
                <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
                <path d="M21 21v-5h-5" />
              </svg>
            </button>
          </div>
          <select
            value={appState.selectedRepo}
            onchange={handleRepoChange}
            disabled={appState.reposLoading}
            style="width: 100% !important; padding: 6px 8px !important; border-radius: 6px !important; font-size: 13px !important; background: #f5f5f5 !important; border: 1px solid #d4d4d4 !important; color: #262626 !important;"
          >
            <option value="">{appState.reposLoading ? 'Loading...' : 'Select repository...'}</option>
            {#each appState.repos as repo}
              <option value={repo.fullName}>{repo.fullName.split("/")[1]}</option>
            {/each}
          </select>
        </label>

        <label style="display: flex !important; flex-direction: column !important; gap: 4px !important;">
          <span style="font-size: 12px !important; color: #737373 !important;">Branch</span>
          <select
            value={appState.selectedBranch}
            onchange={handleBranchChange}
            disabled={!appState.selectedRepo || appState.branchesLoading}
            style="width: 100% !important; padding: 6px 8px !important; border-radius: 6px !important; font-size: 13px !important; background: #f5f5f5 !important; border: 1px solid #d4d4d4 !important; color: #262626 !important;"
          >
            <option value="">{appState.branchesLoading ? 'Loading...' : 'Select branch...'}</option>
            {#each appState.branches as branch}
              <option value={branch.name}>{branch.name}</option>
            {/each}
          </select>
          {#if appState.branchesError}
            <span style="font-size: 11px !important; color: #ef4444 !important;">Failed to load branches</span>
          {/if}
        </label>
      </div>
    </div>
  {:else}
    <button
      type="button"
      style="
        display: flex !important;
        align-items: center !important;
        gap: 8px !important;
        width: 100% !important;
        padding: 10px 12px !important;
        border-radius: 8px !important;
        font-size: 13px !important;
        font-weight: 500 !important;
        cursor: pointer !important;
        border: 1px solid #d4d4d4 !important;
        background: #f5f5f5 !important;
        color: #262626 !important;
        transition: all 0.15s ease !important;
      "
      onclick={onConnect}
    >
      <img src={gitLogo} alt="" style="width: 18px !important; height: 18px !important;" />
      <span>Connect to GitHub</span>
    </button>
  {/if}
</div>

// src/content/components/GitHubSection.tsx
import gitLogo from '../../assets/git.svg'
import { useAppStore } from '../store'

interface Props {
  connected?: boolean
  onConnect?: () => void
  onDisconnect?: () => void
}

export function GitHubSection({ connected = false, onConnect, onDisconnect }: Props) {
  const repos = useAppStore((s) => s.repos)
  const branches = useAppStore((s) => s.branches)
  const selectedRepo = useAppStore((s) => s.selectedRepo)
  const selectedBranch = useAppStore((s) => s.selectedBranch)
  const reposLoading = useAppStore((s) => s.reposLoading)
  const reposError = useAppStore((s) => s.reposError)
  const branchesLoading = useAppStore((s) => s.branchesLoading)
  const branchesError = useAppStore((s) => s.branchesError)
  const setSelectedRepo = useAppStore((s) => s.setSelectedRepo)
  const setSelectedBranch = useAppStore((s) => s.setSelectedBranch)
  const fetchRepos = useAppStore((s) => s.fetchRepos)

  function handleRepoChange(event: React.ChangeEvent<HTMLSelectElement>) {
    setSelectedRepo(event.target.value)
  }

  function handleBranchChange(event: React.ChangeEvent<HTMLSelectElement>) {
    setSelectedBranch(event.target.value)
  }

  function handleRefresh() {
    fetchRepos(true)
  }

  return (
    <div className="flex flex-col gap-3">
      <div className="text-[11px] font-semibold text-neutral-500 uppercase tracking-wide">
        GitHub
      </div>

      {connected ? (
        <div className="flex flex-col gap-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-sm text-emerald-500">
              <img src={gitLogo} alt="" className="w-4 h-4" />
              <span>Connected</span>
            </div>
            <button
              type="button"
              className="text-xs text-neutral-500 bg-transparent border-none cursor-pointer"
              onClick={onDisconnect}
            >
              Disconnect
            </button>
          </div>

          {reposError && (
            <div className="text-xs text-red-500 p-2 bg-red-50 rounded-md">
              {reposError}
            </div>
          )}

          <div className="flex flex-col gap-2">
            <label className="flex flex-col gap-1">
              <div className="flex items-center justify-between">
                <span className="text-xs text-neutral-500">Repository</span>
                <button
                  type="button"
                  onClick={handleRefresh}
                  disabled={reposLoading}
                  title="Refresh repositories"
                  className="bg-transparent border-none p-0.5 cursor-pointer text-neutral-500 flex items-center justify-center"
                >
                  <svg
                    className={`w-3.5 h-3.5 ${reposLoading ? 'animate-spin' : ''}`}
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8" />
                    <path d="M3 3v5h5" />
                    <path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16" />
                    <path d="M21 21v-5h-5" />
                  </svg>
                </button>
              </div>
              <select
                value={selectedRepo}
                onChange={handleRepoChange}
                disabled={reposLoading}
                className="w-full px-2 py-1.5 rounded-md text-[13px] bg-neutral-100 border border-neutral-300 text-neutral-800"
              >
                <option value="">{reposLoading ? 'Loading...' : 'Select repository...'}</option>
                {repos.map((repo) => (
                  <option key={repo.fullName} value={repo.fullName}>
                    {repo.fullName.split('/')[1]}
                  </option>
                ))}
              </select>
            </label>

            <label className="flex flex-col gap-1">
              <span className="text-xs text-neutral-500">Branch</span>
              <select
                value={selectedBranch}
                onChange={handleBranchChange}
                disabled={!selectedRepo || branchesLoading}
                className="w-full px-2 py-1.5 rounded-md text-[13px] bg-neutral-100 border border-neutral-300 text-neutral-800"
              >
                <option value="">{branchesLoading ? 'Loading...' : 'Select branch...'}</option>
                {branches.map((b) => (
                  <option key={b.name} value={b.name}>
                    {b.name}
                  </option>
                ))}
              </select>
              {branchesError && (
                <span className="text-[11px] text-red-500">Failed to load branches</span>
              )}
            </label>
          </div>
        </div>
      ) : (
        <button
          type="button"
          className="flex items-center gap-2 w-full px-3 py-2.5 rounded-lg text-[13px] font-medium cursor-pointer border border-neutral-300 bg-neutral-100 text-neutral-800 transition-all duration-150"
          onClick={(e) => {
            e.stopPropagation()
            onConnect?.()
          }}
        >
          <img src={gitLogo} alt="" className="w-[18px] h-[18px]" />
          <span>Connect to GitHub</span>
        </button>
      )}
    </div>
  )
}
